// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgapzbqruvfxsrhrwvqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYXB6YnFydXZmeHNyaHJ3dnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjIwMzcsImV4cCI6MjA3MzE5ODAzN30._NmDtl3Lxz39q-e3OZqQ5If9KJ0ywV24YjOsSyERxr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});